### PR TITLE
Fix frame compilation. add docs

### PR DESCRIPTION
**Pull request by suranyami**
* Was getting a compilation error in `frame.ex`, so fixed the dialyzer spec and match correct params.
* Updated `README.md` to have example usage of router and explanations on obtaining message_definition files.
* Set explicit directories for `message_definitions` and `output`, and added them to `.gitignore`.
* Removed really noisy logging when seeing an unrecognised message. It was making debugging anything impossible.

### CODE REVIEW

**Review by mynameisrufus — APPROVED** [review]

**Comment by suranyami** [comment]
Hey, @mynameisrufus… it seems like you have admin rights for the beamuav organisation... do you wanna add me to it?

**Comment by robinhilliard** [comment]
Hey Dave I'll get receiving and sending working then have another go at bringing this stuff in - there have been lots of changes.

**Comment by suranyami** [comment]
I'll rebase this off `master`, then merge it so it'll have less conflicts with what you're doing.

**Comment by suranyami** [comment]
Closing this PR, because too many conflicts and issue was fixed on `master`.

**Pull request closed without merging**
